app:
  root:
    url: e-commerce/api/v1

spring:
  datasource:
    url: jdbc:postgresql://Postgres:5432/postgres
    password: admin
    username: admin
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate.format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

redis:
  host: redis
  port: 6379

jwt:
  secret: eCommerceTaskSecretKey!@#123
  expiration: 7_200_000
  header: Authorization
  route:
    authentication:
      path: auth
